import { describe, it, expect } from 'vitest';
import { emitDTS } from '../../emitters/typescript/dts-emitter.js';
import type {
  IonIRModule,
  IonIRNode,
  LetNode,
  LiteralNode,
  AbsNode,
  AdtDeclNode,
  OopClassNode,
  OopInterfaceNode,
  OopMethod,
  OopMember,
  EffectDeclNode,
  RawInjectNode,
  ForeignRefNode,
  VarNode,
  Param,
} from '../../src/ir/nodes.js';
import type { IonType } from '../../src/ir/types.js';
import type { Span } from '../../src/types.js';
import type { SymbolId } from '../../src/types.js';

// ---------------------------------------------------------------------------
// Shared test helpers
// ---------------------------------------------------------------------------

const S: Span = { file: '', startLine: 0, startCol: 0, endLine: 0, endCol: 0 };
const sym = (s: string): SymbolId => s as SymbolId;

const INT: IonType = { kind: 'Int' };
const STR: IonType = { kind: 'Str' };
const BOOL: IonType = { kind: 'Bool' };
const VOID: IonType = { kind: 'Unit' };
const FN2_INT: IonType = { kind: 'Fn', params: [INT, INT], ret: INT, effects: new Set() };

function makeVar(name: string, type: IonType = INT): VarNode {
  return { kind: 'Var', name, symbolId: sym(name), span: S, type };
}

function makeLiteralInt(n: number): LiteralNode {
  return { kind: 'Literal', value: { kind: 'Int', value: n }, span: S, type: INT };
}

function makeLet(name: string, value: IonIRNode, bindingType?: IonType): LetNode {
  return {
    kind: 'Let',
    name,
    symbolId: sym(name),
    bindingType: bindingType ?? value.type,
    value,
    body: makeVar(name, bindingType ?? value.type),
    span: S,
    type: bindingType ?? value.type,
  };
}

function makeModule(decls: readonly IonIRNode[], data: readonly AdtDeclNode[] = []): IonIRModule {
  return {
    ionir: '1.0',
    module: 'test',
    version: '0.1.0',
    dialects: ['core'],
    imports: [],
    data,
    decls,
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('emitDTS', () => {
  it('empty module emits only the header comment', () => {
    const mod = makeModule([]);
    const out = emitDTS(mod);
    expect(out.trim()).toBe('// Generated by ION — do not edit');
  });

  it('simple const let emits export declare const with type', () => {
    const mod = makeModule([makeLet('answer', makeLiteralInt(42))]);
    const out = emitDTS(mod);
    expect(out).toContain('export declare const answer: number;');
  });

  it('function let emits export declare const with Fn type', () => {
    const abs: AbsNode = {
      kind: 'Abs',
      params: [
        { name: 'a', symbolId: sym('a'), type: INT, span: S },
        { name: 'b', symbolId: sym('b'), type: INT, span: S },
      ],
      body: makeVar('a'),
      captures: [],
      span: S,
      type: FN2_INT,
    };
    const mod = makeModule([makeLet('add', abs, FN2_INT)]);
    const out = emitDTS(mod);
    expect(out).toContain('export declare const add: (_0: number, _1: number) => number;');
  });

  it('ADT without fields emits union type and declare const', () => {
    const adtDecl: AdtDeclNode = {
      kind: 'AdtDecl',
      name: 'Color',
      symbolId: sym('Color'),
      variants: [
        { tag: 'Red', symbolId: sym('Red'), fields: [], span: S },
        { tag: 'Green', symbolId: sym('Green'), fields: [], span: S },
      ],
      span: S,
      type: { kind: 'User', name: 'Color', symbolId: sym('Color'), args: [] },
    };
    const mod = makeModule([], [adtDecl]);
    const out = emitDTS(mod);
    expect(out).toContain('export type Color = { _tag: "Red" } | { _tag: "Green" };');
    expect(out).toContain('export declare const Red: Color;');
    expect(out).toContain('export declare const Green: Color;');
  });

  it('ADT with fields emits factory function declare', () => {
    const adtDecl: AdtDeclNode = {
      kind: 'AdtDecl',
      name: 'Shape',
      symbolId: sym('Shape'),
      variants: [
        {
          tag: 'Circle',
          symbolId: sym('Circle'),
          fields: [{ name: 'radius', symbolId: sym('radius'), type: INT, span: S }],
          span: S,
        },
      ],
      span: S,
      type: { kind: 'User', name: 'Shape', symbolId: sym('Shape'), args: [] },
    };
    const mod = makeModule([], [adtDecl]);
    const out = emitDTS(mod);
    expect(out).toContain('export type Shape = { _tag: "Circle"; radius: number };');
    expect(out).toContain('export declare const Circle: (radius: number) => Shape;');
  });

  it('OopInterface emits export interface with property and method members', () => {
    const nameField: OopMember = {
      name: 'name',
      symbolId: sym('name'),
      type: STR,
      span: S,
    };
    const speakMethod: OopMember = {
      name: 'speak',
      symbolId: sym('speak'),
      type: { kind: 'Fn', params: [], ret: VOID, effects: new Set() },
      span: S,
    };
    const iface: OopInterfaceNode = {
      kind: 'OopInterface',
      name: 'Animal',
      symbolId: sym('Animal'),
      members: [nameField, speakMethod],
      span: S,
      type: { kind: 'User', name: 'Animal', symbolId: sym('Animal'), args: [] },
    };
    const mod = makeModule([iface]);
    const out = emitDTS(mod);
    expect(out).toContain('export interface Animal {');
    expect(out).toContain('  name: string;');
    expect(out).toContain('  speak(): void;');
  });

  it('OopInterface with type params emits generic interface', () => {
    const valueField: OopMember = {
      name: 'value',
      symbolId: sym('value'),
      type: { kind: 'TypeVar', id: 'T' },
      span: S,
    };
    const iface: OopInterfaceNode = {
      kind: 'OopInterface',
      name: 'Box',
      symbolId: sym('Box'),
      members: [valueField],
      typeParams: ['T'],
      span: S,
      type: { kind: 'User', name: 'Box', symbolId: sym('Box'), args: [] },
    };
    const mod = makeModule([iface]);
    const out = emitDTS(mod);
    expect(out).toContain('export interface Box<T> {');
  });

  it('OopClass emits declare class with superclass, implements, type params, field, method', () => {
    const method: OopMethod = {
      name: 'area',
      symbolId: sym('area'),
      params: [],
      retType: INT,
      isAbstract: false,
      isStatic: false,
      span: S,
    };
    const cls: OopClassNode = {
      kind: 'OopClass',
      name: 'Circle',
      symbolId: sym('Circle'),
      superClass: sym('Shape'),
      interfaces: [sym('Drawable')],
      typeParams: ['T'],
      fields: [{ name: 'radius', symbolId: sym('radius'), type: INT, span: S }],
      methods: [method],
      span: S,
      type: { kind: 'User', name: 'Circle', symbolId: sym('Circle'), args: [] },
    };
    const mod = makeModule([cls]);
    const out = emitDTS(mod);
    expect(out).toContain('export declare class Circle<T> extends Shape implements Drawable {');
    expect(out).toContain('  radius: number;');
    expect(out).toContain('  constructor(radius: number);');
    expect(out).toContain('  area(): number;');
  });

  it('OopClass with private field and abstract method emits visibility + abstract modifiers', () => {
    const method: OopMethod = {
      name: 'render',
      symbolId: sym('render'),
      params: [],
      retType: VOID,
      isAbstract: true,
      isStatic: false,
      span: S,
    };
    const cls: OopClassNode = {
      kind: 'OopClass',
      name: 'Widget',
      symbolId: sym('Widget'),
      interfaces: [],
      fields: [{ name: 'id', symbolId: sym('id'), type: STR, span: S, visibility: 'private' }],
      methods: [method],
      span: S,
      type: { kind: 'User', name: 'Widget', symbolId: sym('Widget'), args: [] },
    };
    const mod = makeModule([cls]);
    const out = emitDTS(mod);
    expect(out).toContain('export declare class Widget {');
    expect(out).toContain('  private id: string;');
    expect(out).toContain('  abstract render(): void;');
  });

  it('EffectDecl emits export type alias', () => {
    const effect: EffectDeclNode = {
      kind: 'EffectDecl',
      name: 'Logger',
      symbolId: sym('Logger'),
      operations: [
        {
          name: 'log',
          params: [{ name: 'msg', symbolId: sym('msg'), type: STR, span: S }],
          retType: VOID,
          span: S,
        },
      ],
      span: S,
      type: { kind: 'User', name: 'Logger', symbolId: sym('Logger'), args: [] },
    };
    const mod = makeModule([effect]);
    const out = emitDTS(mod);
    expect(out).toContain('export type Logger_Effect = { log(msg: string): void };');
  });

  it('RawInject emits verbatim code', () => {
    const raw: RawInjectNode = {
      kind: 'RawInject',
      code: 'export declare function nativeHelper(): void;',
      span: S,
      type: VOID,
    };
    const mod = makeModule([raw]);
    const out = emitDTS(mod);
    expect(out).toContain('export declare function nativeHelper(): void;');
  });

  it('ForeignRef produces no output', () => {
    const ref: ForeignRefNode = {
      kind: 'ForeignRef',
      target: 'ts',
      module: 'console',
      symbol: 'log',
      sig: { params: [STR], ret: VOID, template: 'console.log($1)', paramNames: ['msg'] },
      span: S,
      type: { kind: 'Fn', params: [STR], ret: VOID, effects: new Set() },
    };
    const mod = makeModule([ref]);
    const out = emitDTS(mod);
    // Only the header comment
    expect(out.trim()).toBe('// Generated by ION — do not edit');
  });

  it('Let with Option type emits nullable type', () => {
    const optType: IonType = { kind: 'Option', inner: INT };
    const fnType: IonType = {
      kind: 'Fn',
      params: [{ kind: 'List', elem: INT }],
      ret: optType,
      effects: new Set(),
    };
    const mod = makeModule([makeLet('find', makeVar('find', fnType), fnType)]);
    const out = emitDTS(mod);
    expect(out).toContain('export declare const find: (_0: number[]) => number | null;');
  });

  it('header comment is the first line', () => {
    const mod = makeModule([makeLet('x', makeLiteralInt(1))]);
    const out = emitDTS(mod);
    expect(out.startsWith('// Generated by ION — do not edit\n')).toBe(true);
  });

  it('output ends with a newline', () => {
    const mod = makeModule([]);
    const out = emitDTS(mod);
    expect(out.endsWith('\n')).toBe(true);
  });

  it('emits multiple lets in module order', () => {
    const mod = makeModule([
      makeLet('a', makeLiteralInt(1)),
      makeLet('b', makeLiteralInt(2)),
    ]);
    const out = emitDTS(mod);
    const ia = out.indexOf('declare const a:');
    const ib = out.indexOf('declare const b:');
    expect(ia).toBeGreaterThan(-1);
    expect(ib).toBeGreaterThan(ia);
  });
});
